apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    routers:
    - protocol: http
      label: outgoing
      servers:
      - port: 4140
        ip: 0.0.0.0
      baseDtab: |
        /host      => /#/io.l5d.k8s/default/http;
        /http/*/*  => /host;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: incoming
          service: linkerd

    - protocol: http
      label: incoming
      dstPrefix: /
      identifier:
        kind: io.l5d.header
        header: l5d-dst-concrete
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0
